"""added procerment assginee to request

Revision ID: 0e0b6359a000
Revises: 3532327cc60d
Create Date: 2026-05-13 12:07:58.078635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0b6359a000'
down_revision: Union[str, Sequence[str], None] = '3532327cc60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('procurement_manager_id', sa.UUID(), nullable=False),
    sa.Column('rfq_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'QUOTE_RECEIVED', 'DECLINED', name='rfqstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procurement_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_number')
    )
    op.add_column('requests', sa.Column('procurement_assigned_to_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('requests_sales_manager_id_fkey'), 'requests', type_='foreignkey')
    op.drop_constraint(op.f('requests_created_by_user_id_fkey'), 'requests', type_='foreignkey')
    op.drop_constraint(op.f('requests_assigned_to_user_id_fkey'), 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'users', ['sales_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'requests', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'requests', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'requests', 'users', ['procurement_assigned_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key(op.f('requests_assigned_to_user_id_fkey'), 'requests', 'users', ['assigned_to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('requests_created_by_user_id_fkey'), 'requests', 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('requests_sales_manager_id_fkey'), 'requests', 'users', ['sales_manager_id'], ['id'], ondelete='CASCADE')
    op.drop_column('requests', 'procurement_assigned_to_id')
    op.drop_table('rfqs')
    # ### end Alembic commands ###
