"""updated doc item

Revision ID: 0e9e75954d95
Revises: a6d31b8226db
Create Date: 2026-05-21 21:59:47.762890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9e75954d95'
down_revision: Union[str, Sequence[str], None] = 'a6d31b8226db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_item_item_id_fkey'), 'documents_item', type_='foreignkey')
    op.drop_column('documents_item', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_item', sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('documents_item_item_id_fkey'), 'documents_item', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
