"""create rfqs quotations offers offer_versions

Revision ID: 1d26df5cb087
Revises: 4385dcdd6fbe
Create Date: 2026-05-17 16:49:56.327960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d26df5cb087'
down_revision: Union[str, Sequence[str], None] = '4385dcdd6fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('offer_number', sa.String(length=100), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_number')
    )
    op.create_table('offer_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_COD_APPROVAL', 'COD_APPROVED', 'COD_REJECTED', 'CHANGES_REQUESTED', 'SENT_TO_CLIENT', 'CLIENT_APPROVED', 'CLIENT_REJECTED', 'REVISION_REQUESTED', name='offerstatus'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_price_letters', sa.String(length=500), nullable=True),
    sa.Column('payment_terms', sa.String(length=500), nullable=True),
    sa.Column('delivery_terms', sa.String(length=500), nullable=True),
    sa.Column('delivery_period', sa.String(length=200), nullable=True),
    sa.Column('validity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country_of_origin', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cod_notes', sa.Text(), nullable=True),
    sa.Column('cod_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('cod_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('client_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cod_approved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_versions')
    op.drop_table('offers')
    # ### end Alembic commands ###
