"""rename cod approval fields in offer_versions

Revision ID: 1dea4ced4380
Revises: a9bb8ad5fa77
Create Date: 2026-05-19 12:43:16.740653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dea4ced4380'
down_revision: Union[str, Sequence[str], None] = 'a9bb8ad5fa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_versions', sa.Column('cod_actioned_by_id', sa.UUID(), nullable=True))
    op.add_column('offer_versions', sa.Column('cod_actioned_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('offer_versions_cod_approved_by_id_fkey'), 'offer_versions', type_='foreignkey')
    op.create_foreign_key(None, 'offer_versions', 'users', ['cod_actioned_by_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('offer_versions', 'cod_approved_by_id')
    op.drop_column('offer_versions', 'cod_approved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_versions', sa.Column('cod_approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('offer_versions', sa.Column('cod_approved_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offer_versions', type_='foreignkey')
    op.create_foreign_key(op.f('offer_versions_cod_approved_by_id_fkey'), 'offer_versions', 'users', ['cod_approved_by_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('offer_versions', 'cod_actioned_at')
    op.drop_column('offer_versions', 'cod_actioned_by_id')
    # ### end Alembic commands ###
