"""create rfqs quotations

Revision ID: 2ff876eb71f1
Revises: 0e0b6359a000
Create Date: 2026-05-13 15:32:26.309887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff876eb71f1'
down_revision: Union[str, Sequence[str], None] = '0e0b6359a000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'UNDER_REVIEW', 'SELECTED', 'REJECTED', name='quotationstatus'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('payment_terms', sa.String(length=500), nullable=True),
    sa.Column('delivery_terms', sa.String(length=500), nullable=True),
    sa.Column('lead_time', sa.String(length=200), nullable=True),
    sa.Column('validity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_for_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('rfqs', 'rfq_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('rfqs_procurement_manager_id_fkey'), 'rfqs', type_='foreignkey')
    op.create_foreign_key(None, 'rfqs', 'users', ['procurement_manager_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.create_foreign_key(op.f('rfqs_procurement_manager_id_fkey'), 'rfqs', 'users', ['procurement_manager_id'], ['id'], ondelete='SET NULL')
    op.alter_column('rfqs', 'rfq_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_table('quotations')
    # ### end Alembic commands ###
