"""add quotation client_refrence

Revision ID: 4385dcdd6fbe
Revises: e4bab3933773
Create Date: 2026-05-17 11:28:06.815236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4385dcdd6fbe'
down_revision: Union[str, Sequence[str], None] = 'e4bab3933773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('client_reference', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'client_reference')
    # ### end Alembic commands ###
