"""phone number are no longer unique in client and supplier

Revision ID: 54f0b82b9004
Revises: 0e9e75954d95
Create Date: 2026-06-07 13:36:32.028955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f0b82b9004'
down_revision: Union[str, Sequence[str], None] = '0e9e75954d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_phone_1_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_phone_2_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('suppliers_email_key'), 'suppliers', type_='unique')
    op.drop_constraint(op.f('suppliers_phone_1_key'), 'suppliers', type_='unique')
    op.drop_constraint(op.f('suppliers_phone_2_key'), 'suppliers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('suppliers_phone_2_key'), 'suppliers', ['phone_2'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('suppliers_phone_1_key'), 'suppliers', ['phone_1'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('suppliers_email_key'), 'suppliers', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_phone_2_key'), 'clients', ['phone_2'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_phone_1_key'), 'clients', ['phone_1'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
