"""create document_items

Revision ID: 667c0a4e95be
Revises: 1d26df5cb087
Create Date: 2026-05-18 13:07:16.288001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '667c0a4e95be'
down_revision: Union[str, Sequence[str], None] = '1d26df5cb087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('REQUEST', 'RFQ', 'QUOTATION', 'OFFER_VERSION', 'PURCHASE_ORDER', 'SHIPMENT', name='documenttype'), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('warranty', sa.String(length=200), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('hs_code', sa.String(length=50), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimensions_cm', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents_item')
    # ### end Alembic commands ###
