"""added purchase_order table

Revision ID: 6c4691efb03a
Revises: b3891dc57f93
Create Date: 2026-05-20 12:01:03.137602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4691efb03a'
down_revision: Union[str, Sequence[str], None] = 'b3891dc57f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_version_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACKNOWLEDGED', 'CLOSED', name='postatus'), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('lead_time', sa.Text(), nullable=True),
    sa.Column('validity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_version_id'], ['offer_versions.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
