"""rename client_reference to supplier_reference in quotations

Revision ID: 76f57477a5db
Revises: 1dea4ced4380
Create Date: 2026-05-19 14:22:38.085160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f57477a5db'
down_revision: Union[str, Sequence[str], None] = '1dea4ced4380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('supplier_reference', sa.String(length=100), nullable=False))
    op.drop_column('quotations', 'client_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('client_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('quotations', 'supplier_reference')
    # ### end Alembic commands ###
