"""

Revision ID: a6d31b8226db
Revises: 3d1ebd622a5c
Create Date: 2026-05-20 17:23:36.077127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d31b8226db'
down_revision: Union[str, Sequence[str], None] = '3d1ebd622a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
