"""document item updated

Revision ID: a9bb8ad5fa77
Revises: 667c0a4e95be
Create Date: 2026-05-18 13:24:49.385647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bb8ad5fa77'
down_revision: Union[str, Sequence[str], None] = '667c0a4e95be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_item', sa.Column('unit', sa.String(length=50), nullable=True))
    op.drop_column('documents_item', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_item', sa.Column('price', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('documents_item', 'unit')
    # ### end Alembic commands ###
