"""fixed quotation id in offer table

Revision ID: b3891dc57f93
Revises: 8783372e71d3
Create Date: 2026-05-19 16:29:38.913937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3891dc57f93'
down_revision: Union[str, Sequence[str], None] = '55a6bee1c499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('offers_quotation_id_fkey'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'quotations', ['quotation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_quotation_id_fkey'), 'offers', 'quotations', ['quotation_id'], ['id'])
    # ### end Alembic commands ###
