"""add quotation_number and superseded status

Revision ID: e4bab3933773
Revises: 2ff876eb71f1
Create Date: 2026-05-16 14:37:22.107690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bab3933773'
down_revision: Union[str, Sequence[str], None] = '2ff876eb71f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('quotation_number', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'quotations', ['quotation_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', type_='unique')
    op.drop_column('quotations', 'quotation_number')
    # ### end Alembic commands ###
