"""make phone_2 nullable for clients and suppliers

Revision ID: ea8b6025ca2d
Revises: 114e6af550b9
Create Date: 2026-05-09 12:35:57.375801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8b6025ca2d'
down_revision: Union[str, Sequence[str], None] = '114e6af550b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'phone_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('suppliers', 'phone_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'phone_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'phone_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
